variable "vpc" {}
variable "env" {}
variable "management_vpc" {}
variable "docdb" {}
variable "rds" {}
#variable "elasticache" {}
#variable "rabbitmq" {}
#variable "apps" {}
variable "BASTION_NODE" {}
variable "PROMETHEUS_NODE" {}
#variable "alb" {}
variable "private_zone_id" {}
#variable "public_zone_id" {}
